streamline storage model for raft + forward to leader
Summary:
Changes the semantic model to do versioning in the leader above the storage layer. That lets us re-create caches more easily for coordinator and in the leader pre- and post-commit. We also want the option to join same-tenant updates to limit raft chatter.

Leader has a single apply thread. Most boilerplate wrt request switching is delegated to a Writer.

```
% splitterctl --insecure -e :8800 domains list foo
Error: rpc error: code = NotFound desc = not found
rpc error: code = NotFound desc = not found

% splitterctl --insecure -e :8800 tenants new foo centralus
{
  "tenant": {
    "name": "foo",
    "config": {
      "region": "centralus"
    },
    "created": "2023-09-13T23:40:39.845801194Z"
  },
  "version": "1",
  "timestamp": "2023-09-13T23:40:39.846863986Z"
}

% splitterctl --insecure -e :8800 tenants new foo centralus
Error: rpc error: code = AlreadyExists desc = already exists
rpc error: code = AlreadyExists desc = already exists

% splitterctl --insecure -e :8800 domains new foo/bar/baz
{
  "domain": {
    "name": {
      "service": {
        "tenant": "foo",
        "service": "bar"
      },
      "name": "baz"
    },
    "type": "UNIT",
    "state": "ACTIVE",
    "config": {},
    "created": "2023-09-13T23:41:08.103378582Z"
  },
  "version": "1",
  "timestamp": "2023-09-13T23:41:08.104173457Z"
}

% splitterctl --insecure -e :8800 domains list foo | jq
{
  "domain": {
    "name": {
      "service": {
        "tenant": "foo",
        "service": "bar"
      },
      "name": "baz"
    },
    "type": "UNIT",
    "state": "ACTIVE",
    "config": {},
    "created": "2023-09-13T23:41:08.103378582Z"
  },
  "version": "1",
  "timestamp": "2023-09-13T23:41:08.104173457Z"
}

% splitterctl --insecure -e :8500 domains list foo | jq
{
  "domain": {
    "name": {
      "service": {
        "tenant": "foo",
        "service": "bar"
      },
      "name": "baz"
    },
    "type": "UNIT",
    "state": "ACTIVE",
    "config": {},
    "created": "2023-09-13T23:41:08.103378582Z"
  },
  "version": "1",
  "timestamp": "2023-09-13T23:41:08.104173457Z"
}

```

GitOrigin-RevId: 491d2725a432125b6b4e1a417a0175565b2ac8a2